org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
android.overridePathCheck=true
android.suppressUnsupportedCompileSdk=35
systemProp.http.proxyHost=10.0.0.30
systemProp.http.proxyPort=3128
systemProp.https.proxyHost=10.0.0.30
systemProp.https.proxyPort=3128
kotlin.code.style=official
